import { Inter } from "next/font/google";

import 'vComponents/styles/generated/output.css'
import 'vComponents/styles/generated/bgColors.min.css'
import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
